<?php

/**
 * @file
 * Contains page_logger.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function page_logger_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the page_logger module.
    case 'help.page.page_logger':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Page view log') . '</p>';
      return $output;

    default:
  }
}
